### ISSUE TITLE
importing dripline.core.Interface returns "fail!" message

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#121]
Whenever I am in a python environment and import Interface, I get 2 fail messages. 

```
In [1]: from dripline.core import Interface                                                                           
fail!
fail!

```
But the Interface works as expected.

**Comment by raphaelcervantes** [comment]
I finally understand why this is happening!
It comes from here: https://github.com/driplineorg/controls-guide/blob/3a86af63d6dc11d3e262bd59033b64af2921301c/examples/dripline-python-plugin/dripline/extensions/jitter/__init__.py#L11

I guess this issue is solved.

**Comment by laroque** [comment]
Yeah, this issue was useful though because that line should be removed. I included it when I was testing out something related to how plugins work and never cleaned it up.

I'm going to reopen this issue to clean it up, but feel free to unsubscribe if you're getting noise from the issue.
