### ISSUE TITLE
pybind for return code not passing tests

### ISSUE THREAD

**Issue by yadiw** [driplineorg/dripline-python#59]
new return codes being added using `dripline.core.add_return_code()` seem to be (randomly?) removed right after the function call?
https://github.com/driplineorg/dripline-python/blob/e316213eefea6d71e0b18aa160bcc0e6ef82f246/tests/test_return_codes.py#L24

**Comment by laroque** [comment]
Resolved by https://github.com/driplineorg/dripline-cpp/pull/43

**Comment by laroque** [comment]
above merged/released, dependency updated -> resolved.
