### ISSUE TITLE
unit tests for do_set_request cause segmentation fault

### ISSUE THREAD

**Issue by yadiw** [driplineorg/dripline-python#63]
In unit tests for `dripline.core.Endpoint`, for its method `on_set_request()`:

In tests `test_do_set_request_valid_specifier()`, `test_do_set_request_invalid_specifier()`:
- expected: AssertionError being raised due to the problem discussed in another issue
- actual: a segmentation fault occurs at the place where the AssertionError is supposed to be raised. It might not happen when the method is run for the first time, but would definitely happen if it is run for more than once.

In test `test_do_set_request_no_specifier()`:
- expected: it passes all assertions and nothing happens.
- actual: a segmentation fault occurs at the end of the function, after passing every assertion.

**Comment by laroque** [comment]
It isn't yet clear if this is an actual bug, or something related to the behavior of running within the testing framework. I'll need to dig into this to either work around details of how pytest works, or identify an issue if it is in dripline-cpp

**Comment by laroque** [comment]
There was a bug in the python bindings for scarab, resolved in: https://github.com/project8/scarab/pull/66. That's been merged into develop in dripline-cpp and we just await a release to update here.

**Comment by laroque** [comment]
resolved/merged/released
