### ISSUE TITLE
do_set_request() returns wrong reply with (in)valid specifier

### ISSUE THREAD

**Issue by yadiw** [driplineorg/dripline-python#64]
In unit tests for `dripline.core.Endpoint`, for its method `on_set_request()`:

Given a request with a valid specifier:
- expected: the value of the existing attribute is updated, a reply with return code 0 is returned
- actual: the value of the existing attribute is not updated, a reply with return code 201 is returned

Given a request with an invalid specifier:
- expected: a reply with return code 201 is returned
- actual: a new attribute with given value is added to the endpoint, a reply with return code 0 is returned

p.s. if we run these tests for more than once, an segmentation fault would occur, and this is discussed in another issue.

**Comment by laroque** [comment]
In the tests, the methods now handle the ThrowReply producing those errors, this is resolved on branch `dl3/unittest-fixes` (No PR yet because it requires `driplineorg/dripline-cpp:develop`)

**Comment by laroque** [comment]
done last friday
