### ISSUE TITLE
I want to add kubernetes kv-store example

### ISSUE THREAD

**Issue by raphaelcervantes** [driplineorg/dripline-python#85]
I have the[ tutorial kv-store example](https://driplineorg.github.io/controls-guide/develop/guides/first-mesh.html) working in a kubernetes setting. I was thinking of pushing my kubernetes/helm structure for anyone else that is interested, but I am unable to add a new branch onto this repo. Is there interest in posting my example?

**Comment by laroque** [comment]
There is interest. Please create a fork (button in the upper right) and push your branch to your repo. From there you should be able to create a pull request back to the driplineorg repo, where we can review/discuss and then merge the changes.

However, tutorials belong in the [controls-guide](github.com/driplineorg/controls-guide) repo. There is an examples folder that would be the place to hold your values files, and then ideally text notes/description would go in an rst file in the source folder to be built into a tutorial page.

**Comment by raphaelcervantes** [comment]
Ok. I will work on it when I get the chance. Thank you.

**Comment by laroque** [comment]
Thanks @raphaelcervantes. I'd say that there are three useful stages, any one of which is worth going ahead and putting in the PR unless you're actively working on an even better stage:
1. a set of working values files for running the tutorial components without any prose.
2. (1) + a minimal prose description that says a little about what is there, how to get started, or links out to official docs for helm etc., but doesn't really walk the reader through the process.
3. (1) or (2) + a more complete "tutorial" which walks through the steps and encourages the reader notice or interact with components at various steps along the way (and also links out to official docs for tools we leverage, like helm etc.)

The goal is to have level 3 everywhere in the guide, but 1 or 2 is better than nothing and provides a stepping stone for someone else to fill it out to the later stages.

**Comment by nsoblath** [comment]
I should also note that there's interest from others in having more information about a Kubernetes deployment.  I just got off a meeting that included a discussion of the dripline3 with someone who had done a review of the dripline documentation, and he was specifically interested in hearing more about this topic, including why one might choose to use Kubernetes, and what it would take to do that versus docker-compose.

**Comment by raphaelcervantes** [comment]
Ok. I will prioritize an example tomorrow and some documentations tomorrow!

**Comment by raphaelcervantes** [comment]
@laroque I think I did the pull request properly.
https://github.com/driplineorg/dripline-python/pull/89

**Comment by raphaelcervantes** [comment]
Actually, try this pull request: https://github.com/driplineorg/dripline-python/pull/90
